### ISSUE TITLE
Source code hash produced an invalid new value?

### ISSUE THREAD

**Issue by gijs3it** [dealmore/terraform-aws-next-js-image-optimization#14] opened 2021-03-04 11:48 UTC
Hi
This module is used by the tf_next module, which we use to deploy our Next.JS app.
This produces the following error, when running terraform apply:
```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.tf_next.module.next_image[0].module.image_optimizer.aws_lambda_function.this[0]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.source_code_hash: was
cty.StringVal("h9txBCKPF6W7ecw/pOFUqFP4zipcpoPjE6Hm9++6/x4="), but now
cty.StringVal("3Sk8OPUX1gRlFMhCoujmMVi5EZmsoi3GuMwdQfYeSAI=").
```
I am calling the "main" tf_next module with:
```
module "tf_next" {
  version = "v0.7.0"
  source  = "dealmore/next-js/aws"

  next_tf_dir     = "../../.next-tf"
  deployment_name = "terraform-next-js-test"

  # You can also attach multiple domains here since it accepts an array
  # Keep in mind that `domain_names` & `domain_zone_names` should always
  # contain the same number of elements, because a domain uses the same index
  # to get the associated zone_id
  # e.g. domain_names[0] -> domain_zone_names[0]
  #      domain_names[1] -> domain_zone_names[1]
  #      etc.
  domain_names      = [local.domain_name]
  domain_zone_names = [data.aws_route53_zone.main_domain_zone.name]

  # Tell CloudFront to use our created certificate
  cloudfront_viewer_certificate_arn = module.cloudfront_cert.this_acm_certificate_arn
}
```

Which loads this module in "default".
Could I change something to overcome the issue?

**Comment by ofhouse** [comment] 2021-03-04 12:02
Thanks for reporting.
Yes, I saw the same error message in our logs too.

To overcome this issue you could try to run `terraform apply` a second time which should temporary fix the issue.

I have an idea where this misbehaviour comes from but need more time to investigate.

**Comment by gijs3it** [comment] 2021-03-04 12:07
Hi, thanks for your reply. Sadly another apply did not work.
Now trying a destroy/apply again. (Takes some time because of the replicated Lambda.)
Could be because I had some intermediate failures, like; No AWS tooling installed, no `bash`, no `openssl` on my Docker instance... Furthermore some permission Issue with IAM roles, so this might be related...

**Comment by ofhouse** [comment] 2021-03-04 12:21
What I think is causing the issue is the version range (`^10.0.5-beta`) used for fetching the Lambda content from npm for this module.
Requesting the range produces a redirect on the download server which sometimes results in a changed source code hash.

In the main Terraform Next.js version we only use fixed versions for this instead of ranges and I have not experienced a similar issue there.
The idea behind using a version range instead of a fixed version was that we not have to release a new version of this module when a new Next.js version is released.

But I think this doesn't work well enough and we should align the versioning of this module with the Next.js versioning like it was originally planned.

**Comment by gijs3it** [comment] 2021-03-04 12:35
Aaaah, oke that explains more of it. Which version of Next should we "best" test with?

After the destroy and new apply, the error stays the same, which seems in line with your explenation above.
We use "fixed" 10.0.6 now, according to our package.json.

```
 "dependencies": {                                          
    "next": "10.0.6",                             
    "react": "17.0.1",                          
    "react-dom": "17.0.1",                                   
    "sass": "^1.32.6"                             
  },
```
Any further ideas on how to overcome it now? ;-)

**Comment by ofhouse** [comment] 2021-03-04 14:29
Ah, sorry for the confusion here, has nothing to do with the Next.js version from the `package.json` of your installation.

The module itself is built upon the original image optimizer from Next.js.
It gets bundled into a self-containing Lambda function which is published through npm: https://www.npmjs.com/package/@dealmore/tf-next-image-optimization

When applying the Terraform module, Terraform pulls this package from npm and uses it as source code for the Lambda function that is created for doing the image optimization.
We aim to publish a new version of this package every time a new Next.js version is released, to make changes in Next.js available in this module (#10).
Which version of the package is pulled is defined in the [`next_image_version`](https://github.com/dealmore/terraform-aws-next-js-image-optimization/blob/e7de960114713f30cde46ab8691d1e6a7ed10fb2/variables.tf#L4) input variable of the module.

Since we thought that publishing a new Version of this module every time Next.js releases a new version can be time hungry we decided to define a version range per default in the `next_image_version` variable.
Instead we are only publishing a new npm package when something changes.

But resolving the version range of the Lambda package seems to cause a change in the source code hash which likely causes the error here.

---

To fix the issue temporary I have released a new Version [`v0.7.1`](https://github.com/dealmore/terraform-aws-next-js/releases/tag/v0.7.1) of the terraform module.
Inside the `tf_next` block you can now set the version image optimizer package that should be used to a fixed version, like this:
```diff
module "tf_next" {
  version = "v0.7.1"
  source  = "dealmore/next-js/aws"
  ...

+ image_optimization_version =  "10.0.5-beta2"
}
```

**Comment by gijs3it** [comment] 2021-03-04 14:34
oke, thanks for your really fast support!
I finally understood after reading a couple of times (due to my limitations ;-)).
I was already changing:
```
variable "next_image_version" {
  description = "Next.js version from where you want to use the image optimizer from. Supports semver ranges."
  type        = string
  default     = "^10.0.5-beta"
}
```
This part within the module, but supporting it as variable is even greater! Will check that out!
(Now I do not have to look up what the value should be as well..)
Thanks again for the great support! I will let you know how it goes....

**Comment by gijs3it** [comment] 2021-03-04 14:47
Thanks, that is working like it is supposed to! That indeed resolves the issue!

**Comment by ofhouse** [comment] 2021-03-05 17:18
Thanks for letting me know that this works!
Closing this issue for now, but I created a follow-up task for the refactoring the versioning of the module here: #15

**Closed by ofhouse** 2021-03-05 17:18 UTC
Labels: bug
